### ISSUE TITLE
Solution is incorrect

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/guessing-cli#1]
The solution branch is incorrect.
Consider this:
```ruby

  while input
    puts "Guess a number between 1 and 6."
    input = gets.downcase.chomp
    random_number = rand(6).to_s
```
The generator will never produce a `6`, maxing out at `5`. Alternatively, perhaps it could be `rand(1..6)`?

**Comment by AnnJohn** [comment]
Closing issue
