### ISSUE TITLE
Wont accept 1 + rand(6)

### ISSUE THREAD

**Issue by Gonzodamus** [learn-co-curriculum/guessing-cli#5]
When I wrote this code, I used _1 + rand(6)_ instead of _rand(1..6)_ to generate a random number between 1 and 6.  The second passed, while the first returns errors.

**Comment by OlgaEva** [comment]
This is still a problem today, 6/14/2019

**Comment by maxwellbenton** [comment]
Hi @Gonzodamus,

Thank you for opening this issue and providing this feedback. We've updated this lesson's instructions to talk more about the use of `rand`. As ranges are less frequently used, the tests have been updated to work with the syntax you chose, `1+rand(6)`, over using a range, and this has been noted in the instructions to avoid further confusion.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Hope you are well my friend.
